AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity IPV CRI Address API"

Parameters:
  Environment:
    Description: environment name
    Default: dev
    Type: String
    AllowedValues:
      - dev
      - staging
      - integration
      - prod
    ConstraintDescription: specify dev, staging, integration or prod for environment

  OrdinanceSurveyAPIKey:
    Description: Ordinance Survey API Key
    Type: String
    Default: testapikey

Globals:
  Function:
    Timeout: 30 # seconds
    Runtime: java11
    AutoPublishAlias: live
    MemorySize: 512
    Environment:
      Variables:
        AWS_STACK_NAME: !Sub ${AWS::StackName}
        POWERTOOLS_LOG_LEVEL: INFO

Resources:

  AddressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub Environment
#      Auth:
#        DefaultAuthorizer: AWS_IAM
      DefinitionBody:
        openapi: "3.0.1" # workaround to get `sam validate` to work
        paths: # workaround to get `sam validate` to work
          /never-created:
            options: { } # workaround to get `sam validate` to work
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: './api.yaml'
      OpenApiVersion: 3.0.1
      EndpointConfiguration:
        Type: REGIONAL
    DependsOn: [SessionFunction, PostcodeLookupFunction]

  SessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/session
      Handler: uk.gov.di.ipv.cri.address.api.handler.SessionHandler::handleRequest
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - DynamoDBWritePolicy:
            TableName:
              Ref: AddressSessionTable
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/AddressSessionTableName"
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/AddressSessionTtl"
      Events:
        RetrieveSession:
          Type: Api
          Properties:
            Path: /session
            Method: post

  PostcodeLookupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/postcode-lookup
      Handler: uk.gov.di.ipv.cri.address.api.handler.PostcodeLookupHandler::handleRequest
    Policies:
      - AWSLambdaBasicExecutionRole
      - AWSXrayWriteOnlyAccess
      - Statement:
          - Sid: ReadSecretsPolicy
            Effect: Allow
            Action:
              - 'secretsmanager:GetSecretValue'
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${AWS::StackName}/OrdinanceSurveyAPIKey'
    Events:
      PostcodeLookup:
        Type: Api
        Properties:
          Path: /postcode-lookup
          Method: post

  AddressCriCodeSigning:
    Type: AWS::Lambda::CodeSigningConfig
    Properties:
      Description: "Code Signing for Address CRI API"
      AllowedPublishers:
        SigningProfileVersionArns:
          - "{{resolve:ssm:/dev/credentialIssuers/cri/sam/signingProfileVersionArn}}"
      CodeSigningPolicies:
        UntrustedArtifactOnDeployment: "Enforce"

  AddressSessionTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "address-session-${AWS::StackName}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "sessionId"
          AttributeType: "S"
        -
          AttributeName: "authorizationCode"
          AttributeType: "S"
        -
          AttributeName: "token"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "sessionId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: "authorizationCode-index"
          KeySchema:
            -
              AttributeName: "authorizationCode"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "session-id"
            ProjectionType: "INCLUDE"
        -
          IndexName: "token-index"
          KeySchema:
            -
              AttributeName: "token"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "session-id"
            ProjectionType: "INCLUDE"
      TimeToLiveSpecification:
        AttributeName: expiry-date
        Enabled: true

  ParameterAddressSessionTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/AddressSessionTableName"
      Value: !Sub address-session-${AWS::StackName}
      Type: String
      Description: address session dynamodb table name

  ParameterAddressSessionTtl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/AddressSessionTtl"
      Value: 172800 # 2 days
      Type: String
      Description: default time to live for an address session item (seconds)

  SecretOrdinanceSurveyAPIKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${AWS::StackName}/OrdinanceSurveyAPIKey"
      SecretString: !Ref OrdinanceSurveyAPIKey
      Description: API key for the Ordinance Survey API

  SessionFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SessionFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SessionFunction.Arn
      Principal: apigateway.amazonaws.com

  PostcodeLookupFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - PostcodeLookupFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PostcodeLookupFunction.Arn
      Principal: apigateway.amazonaws.com


Outputs:
  SessionFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for session function"
    Value: !Sub "https://${AddressApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/session/"
  SessionFunction:
    Value: !GetAtt SessionFunction.Arn

  PostcodeLookupFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for postcode lookup function"
    Value: !Sub "https://${AddressApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/postcode-lookup/"
  PostcodeLookupFunction:
    Value: !GetAtt PostcodeLookupFunction.Arn