AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity IPV CRI Address API"

Parameters:
  Environment:
    Description: environment name
    Default: dev
    Type: String
    AllowedValues:
      - dev
      - staging
      - integration
      - prod
    ConstraintDescription: specify dev, staging, integration or prod for environment

Globals:
  Function:
    Timeout: 30 # seconds
    Runtime: java11
    AutoPublishAlias: live
    MemorySize: 512
#    PackageType: Zip
#    Architectures:
#      - x86_64

Resources:

  AddressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: address-cri-dev
      DefinitionUri: ./api.yaml
      OpenApiVersion: 3.0.1
      EndpointConfiguration:
        Type: REGIONAL
    DependsOn: SessionFunction

  SessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub cri-address-session-${AWS::StackName}
      CodeUri: ../build/distributions/di-ipv-cri-address-api.zip
      Handler: uk.gov.di.ipv.cri.address.api.handler.SessionHandler

  FunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SessionFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SessionFunction
      Principal: apigateway.amazonaws.com
      ## todo add source arn