name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: di-ipv-cri-address-build
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Gradle build
        run: ./gradlew clean build

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t deploy/template.yaml --config-env ${{ env.ENVIRONMENT }}
      
      - name: SAM build
        run: sam build -t deploy/template.yaml --config-env ${{ env.ENVIRONMENT }}

      - name: SAM package
        run: |
          sam package -t deploy/template.yaml --config-env ${{ env.ENVIRONMENT }} \
            --signing-profiles SessionFunction=${{ secrets.SIGNING_PROFILE_NAME }} \
            PostcodeLookupFunction=${{ secrets.SIGNING_PROFILE_NAME }} \
            AccessTokenFunction=${{ secrets.SIGNING_PROFILE_NAME }} \
            --s3-bucket ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }} \
            --region ${{ env.AWS_REGION }} --output-template-file=cf-template.yaml

      - name: Zip the CloudFormation template
        run: zip template.zip cf-template.yaml

      - name: Upload zipped CloudFormation artifact to S3
        env:
          ARTIFACT_SOURCE_BUCKET_NAME: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
        run: aws s3 cp template.zip "s3://$ARTIFACT_SOURCE_BUCKET_NAME/template.zip"

