name: Deploy to dev
on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/lambda/**'
      - 'gradle/**'
      - 'lambdas/**'
      - 'lib/**'
      - 'build.gradle'
      - 'gradlew'
      - 'settings.gradle'
  workflow_dispatch: # deploy manually

jobs:
  deploy:
    name: deploy-to-dev
    runs-on: ubuntu-latest
    environment: di-ipv-cri-dev
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
      STACK_NAME: di-ipv-cri-address-api-dev
      ROLLBACK_ACTION: "--disable-rollback"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/lambda/template.yaml

      - name: Gradle build
        run: ./gradlew clean build

      - name: SAM build
        run: sam build -t infrastructure/lambda/template.yaml

      - name: SAM deploy
        run: |
          sam deploy -t infrastructure/lambda/template.yaml \
            --no-fail-on-empty-changeset --no-confirm-changeset ${{ env.ROLLBACK_ACTION }} \
            --stack-name ${{ env.STACK_NAME }} --s3-bucket ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }} \
            --s3-prefix ${{ env.STACK_NAME }} --region ${{ env.AWS_REGION }} --capabilities CAPABILITY_IAM
